// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKoy9E_EY5onmvcSfQB8CHs9lC0tTO6NQ',
    appId: '1:1049043976149:web:ab976382fd86c673f3875c',
    messagingSenderId: '1049043976149',
    projectId: 'happify-83672',
    authDomain: 'happify-83672.firebaseapp.com',
    storageBucket: 'happify-83672.appspot.com',
    measurementId: 'G-76E8PSN3QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCweh7w6RTDKQBU4L2u_Enlq5icwRMj_NM',
    appId: '1:1049043976149:android:cf0fde69a8741d62f3875c',
    messagingSenderId: '1049043976149',
    projectId: 'happify-83672',
    storageBucket: 'happify-83672.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwqFJA1A8KrFFnw-EMNlxqqndoou0MtuM',
    appId: '1:1049043976149:ios:170ae6d07efd7c26f3875c',
    messagingSenderId: '1049043976149',
    projectId: 'happify-83672',
    storageBucket: 'happify-83672.appspot.com',
    iosBundleId: 'com.example.happify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwqFJA1A8KrFFnw-EMNlxqqndoou0MtuM',
    appId: '1:1049043976149:ios:e861c071a57977bbf3875c',
    messagingSenderId: '1049043976149',
    projectId: 'happify-83672',
    storageBucket: 'happify-83672.appspot.com',
    iosBundleId: 'com.example.happify.RunnerTests',
  );
}
